app.dynamodb.table-name=url-shortener
app.base-url=https://encurtadorlink.link
app.frontend-url=https://url-shortener-eight-sandy.vercel.app

quarkus.dynamodb.aws.region=us-east-1
quarkus.dynamodb.aws.credentials.type=default
quarkus.dynamodb.devservices.enabled=false

%dev.quarkus.dynamodb.aws.region=us-east-1
%dev.quarkus.dynamodb.aws.credentials.type=default
%dev.app.base-url=http://localhost:8080

%test.quarkus.dynamodb.aws.region=us-east-1
%test.quarkus.dynamodb.aws.credentials.type=default

quarkus.lambda.handler=url-shortener

quarkus.http.cors=true
quarkus.http.cors.origins=https://url-shortener-eight-sandy.vercel.app,https://encurtadorlink.link,http://localhost:5173,http://localhost:3000
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=Content-Type
